version: '3'
services:
  bot:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 5000

  tests:
    build:
      context: .
    volumes:
      - .:/app
    command: sh -c "PYTHONUNBUFFERED=1 pytest"
